### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Unkn0wnCat** [Totonyus/ydl_api#6]
Hey,

I've gone across the [awesome-selfhosted/awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted)-repo and noticed your project does not seem to have any license attached. As such, [you give no-one permission to actually work with your code](https://choosealicense.com/no-permission/).

As such I encourage you to visit https://choosealicense.com/ to find a license that is right for you and your project 🙂 

Kind regards,
Kevin

**Comment by Totonyus** [comment]
Thanks for your feedback. This is a subject I had considered during development but I had chosen the same license as youtube-dl. I realize now that it didn't really make sense.

**Comment by Totonyus** [comment]
Commit a8d9d607a7b313a0357a39f359eb85b649067c61 added
